version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  groups:
    dependencies:
      applies-to: version-updates
      update-types:
      - "minor"
      - "patch"
      patterns:
      - "*"
