baseurl: "/"
languageCode: "en-us"
languageLang: "en"
title: "OWASP ZAP"
enableEmoji: true

taxonomies:
  tag: "tags"

params:
  EditContent:
    BaseUrl: https://github.com/zaproxy/zaproxy-website/blob/master/site/content/
    Label: Edit on GitHub

# Menu
menu:
  nav:
    - name:  "Home"
      URL:  "/"
      weight:  1

    - name:  "Blog"
      URL:  "/blog/"
      weight:  2

    - name:  "ZAP in Ten"
      URL: /zap-in-ten/
      weight:  3

    - name:  Documentation
      URL: /docs/
      weight:  4

    - name:  Get Involved
      URL: /get-involved/
      weight:  5

    - name:  "Support"
      URL:  /support/
      weight:  6


  footer: 
    - name:  "Home"
      URL:  "/"
      weight:  1

    - name:  "Blog"
      URL:  "/blog/"
      weight:  2

    - name:  "ZAP in Ten"
      URL:  /zap-in-ten/
      weight:  3

    - name:  "Get Involved"
      URL:  /get-involved/
      weight:  4

    - name:  "Support"
      URL:  /support/
      weight:  5

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds:  ["RSS", "taxonomy", "taxonomyTerm"]