name: Build site - master

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      
      - name: Install npm dependencies
        run: npm install
      
      - name: Run npm build
        run: npm run build --if-present
      
      - name: Setup ruby for building API docs
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
        
      - name: Import API docs
        run: |  
          git clone https://github.com/zaproxy/zap-api-docs
          cd zap-api-docs
          git pull
          gem install bundler
          bundler install
          bundle exec middleman build --clean
          cp -rf ./build/ ../dist/docs/api
    
      - name: Prepare for release
        run: cd ./dist && zip -r ../latest.zip * && echo "::set-output name=release_path::latest.zip"

      - name: Update the `latest` release
        id: update_release
        uses: ./.github/actions/update-release-assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: 'Latest'
          asset_path: "./latest.zip"
          asset_name: "latest.zip"
              

      # - name: Upload Release Asset
      #   id: upload-release-asset 
      #   uses: actions/upload-release-asset@v1.0.1
      #   env:
      #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #      upload_url: ${{ steps.get_release.outputs.upload_url }}?name=latest.zip
      #      asset_path: latest.zip
      #      asset_name: latest.zip
      #      asset_content_type: application/zip

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v1
      #   with:
      #      name: build
      #      path: ./dist
